export enum EErrorStatusCode {
    // * CONTROLLER
    BODY_VALIDATION_ERROR_GET_ALL_ASSIGN_TODO_GROUP_PROJECT_LIST = "VLD-ER-1000",

    // * REPOSITORY
    REPOSITORY_ERROR_ASSIGN_TODO_GET_USER_ID_BY_USER_USERNAME = "DB-Er-1000",
    REPOSITORY_ERROR_GET_ALL_TODO_IN_GROUP_PROJECT = "DB-ER-1001",
}
